/** SAKINA certificate guide — bilingual explanation of the trust promise behind every documented stone. */
import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowLeft, ArrowRight, BookOpenCheck, HeartHandshake, MapPinned, Sparkles } from "lucide-react";
import { Link } from "wouter";

export default function CertificateGuide() {
  const { language, isArabic } = useLanguage(); const Arrow = isArabic ? ArrowLeft : ArrowRight;
  const copy = isArabic ? { kicker:"وعد سكينة", hero:<>اعرفي حجرَك<br /><em>قبل أن تختاريه.</em></>, body:"الأحجار الطبيعية لا تتشابه، ولذلك لا نرسل لكِ قطعة مجهولة. نضع مع كل اختيار شهادة صغيرة توضح هويته وما يحتاجه ليبقى قريباً منكِ لفترة طويلة.", inside:"داخل شهادة سكينة", title:<>وثيقة هادئة<br />لشيءٍ <em>شخصي.</em></>, proof:"بطاقة مطبوعة ترافق حجرك من أول يوم، تحفظ تفاصيله بوضوح ولا تتركك أمام أسماء عامة أو معلومات مبهمة.", fields:[["اسم الحجر","يُكتب لقطعتك تحديداً"],["النوع","خامة طبيعية موضحة بصدق"],["المصدر","السوق أو المنطقة المختارة منها"],["العناية","خطوات بسيطة تناسب الخامة"]], why:[["مصدر واضح","نذكر المكان الذي بدأت منه رحلة الحجر، من أسواقنا التراثية إلى حقيبتك."],["تفاصيل مفهومة","النوع وطبيعته مكتوبان بلغة بسيطة، لتعرفي ما الذي اخترته فعلاً."],["عناية أقرب","كل خامة لها طريقة حفظ صغيرة، ونتركها معكِ كي تبقى القطعة كما تحبينها."]], cta:"الحجر الذي يليق بكِ يبدأ بمعرفة صادقة.", ctaBody:"اكتشفي القطع الحالية، وستصل شهادتها معكِ أينما كنتِ.", action:"ابدئي الاختيار" } : { kicker:"THE SAKINA PROMISE", hero:<>Know your stone<br /><em>before you choose it.</em></>, body:"Natural stones are never identical, so we never send an anonymous piece. Every selected stone arrives with a small passport explaining its identity and the care it needs to stay close for a long time.", inside:"INSIDE THE SAKINA PASSPORT", title:<>A quiet record<br />for something <em>personal.</em></>, proof:"A printed card that travels with your stone from day one, preserving its details clearly instead of leaving you with generic names or vague information.", fields:[["STONE NAME","Written specifically for your piece"],["TYPE","Natural material, stated honestly"],["SOURCE","The market or place it was selected from"],["CARE","Simple steps suited to the material"]], why:[["Clear source","We name where your stone’s journey started, from heritage markets to your bag."],["Easy details","Type and character are written simply, so you understand exactly what you chose."],["Closer care","Each material needs a small care ritual, and we leave it with you so it stays beautiful."]], cta:"A stone that suits you starts with honest knowledge.", ctaBody:"Discover the current pieces, each one accompanied by its passport wherever you are.", action:"Start choosing" };
  const icons = [MapPinned, BookOpenCheck, HeartHandshake];
  return <main className={`certificate-page lang-${language}`} dir={isArabic ? "rtl" : "ltr"}><div className="route-context"><span>{isArabic ? "أنتِ الآن في" : "You are in"}</span><strong>{isArabic ? "شهادة الحجر" : "Stone passport"}</strong><Link href="/collection">{isArabic ? "الخزانة" : "Cabinet"}</Link></div><section className="certificate-hero"><span className="eyebrow">{copy.kicker}</span><h1>{copy.hero}</h1><p>{copy.body}</p></section><section className="certificate-proof"><div className="proof-copy"><span className="eyebrow">{copy.inside}</span><h2>{copy.title}</h2><p>{copy.proof}</p></div><div className="certificate-sheet"><div className="certificate-sheet__top"><img src="/assets/sakina-mark_d9d397db.png" alt="" /><span>SAKINA · STONE PASSPORT</span></div><div className="certificate-sheet__name">{isArabic ? "وثيقة تعريف الحجر" : "Stone identity record"}</div><div className="certificate-fields">{copy.fields.map(([label, value]) => <p key={label}><span>{label}</span><b>{value}</b></p>)}</div><div className="certificate-stamp">{isArabic ? <>مختار يدوياً<br />من سكينة</> : <>HAND SELECTED<br />BY SAKINA</>}</div></div></section><section className="why-grid">{copy.why.map(([title, body], index) => { const Icon = icons[index]; return <article key={title}><Icon size={24} /><h3>{title}</h3><p>{body}</p></article>; })}</section><section className="certificate-cta"><Sparkles size={21} /><div><h2>{copy.cta}</h2><p>{copy.ctaBody}</p></div><Link href="/collection" className="sun-button">{copy.action} <Arrow size={17} /></Link></section></main>;
}
