/** SAKINA home — the founder story and trust journey, with the stone cabinet moved to its own route. */
import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowLeft, ArrowRight, ArrowUpLeft, BadgeCheck, ShieldCheck, Truck } from "lucide-react";
import { Link } from "wouter";

type Copy = typeof arabicCopy;
const arabicCopy = {
  heroKicker: "من أسواق مصر التراثية إلى باب بيتك", heroTitle: <>اختاري حجراً<br /><em>يشبه هدوءك.</em></>, heroBody: "سكينة تجمع أحجاراً طبيعية مختارة، ثم توثق رحلتها في شهادة خاصة تصل معك أينما كنتِ.", explore: "اكتشفي الخزانة", how: "كيف نختار؟", seal: <>اختيار يدوي<br />وشهادة خاصة</>,
  trust: [["اختيار يدوي", "كل خامة تمر على يدٍ خبيرة قبل أن تصل إليك."], ["شهادة حجر خاصة", "الاسم والنوع وطريقة الحفظ في وثيقة واحدة."], ["لجميع المحافظات", "نغلف كل قطعة بعناية ونوصلها مطمئنة حتى بابك."]],
  originKicker: "الحجر له طريق", originTitle: <>لسنا متجرَ أحجارٍ فقط.<br />نحن نحفظ <em>قصتها.</em></>, originBody: "نبحث عن الحجر الصادق، لا الشكل المتكرر. ثم نمنحه بطاقة تعرفكِ به منذ أول لمسة.",
  steps: [["نختار", "خامات طبيعية من مصادر نعرفها ونعود إليها."], ["نوثّق", "نكتب بطاقة كل قطعة: نوعها وطريقة الحفاظ عليها."], ["نرسل", "نغلفها كقطعة شخصية ونوصلها إلى أي محافظة."]],
  storyKicker: "من سؤال شخصي إلى مكان واحد", storyTitle: <>"أين أجد حجراً <em>نظيفاً</em> وأنا مطمئنة؟"</>, storyOne: "بدأت الفكرة من حب الأشياء التي تُبطئ اليوم وتمنحنا مساحةً هادئة لأنفسنا. لكن الأحجار الطبيعية الجيدة لم تكن دائماً قريبة أو واضحة، وكانت تحتاج وقتاً ومعرفةً لاختيارها.", storyTwo: "لذلك وُجدت سكينة: نجمع هذه الخامات في مكان واحد، ننتقيها بصدق، ونرسل معها ما يعرّفكِ بها حتى تشعري أن اختياركِ له معنى من أول لمسة إلى آخر يوم.", asideTop: "من الأسواق التراثية", asideTitle: <>إلى جميع<br />المحافظات</>, asideBody: "خامة مختارة · تغليف هادئ · شهادة باسم الحجر",
  certificateKicker: "ليست ورقة إضافية", certificateTitle: <>هذه شهادة حجرِك.<br /><em>احفظي قصته.</em></>, certificateBody: "تأتي كل قطعة مختارة مع بطاقة تعريف شخصية تشرح نوعها وطريقة الحفاظ عليها، لتعرفي ما تحملين بين يديك.", certificateLink: "اكتشفي شهادة سكينة", closingKicker: "سكينة معك في كل مكان", closing: "اختاري بهدوء. نختار بصدق. ونوصلُ لكِ ما يستحق أن يصبح جزءاً من طقسِك اليومي.", passportName: "تذكرة تعريف الحجر", passportType: "النوع", passportCare: "العناية", passportTypeText: "حجر طبيعي مختار", passportCareText: "تعليمات خاصة بكل قطعة",
};
const englishCopy: Copy = {
  heroKicker: "FROM EGYPT’S HERITAGE TO YOUR DOOR", heroTitle: <>Choose a stone<br /><em>that feels like calm.</em></>, heroBody: "SAKINA brings together selected natural stones, then documents their journey in a personal certificate delivered wherever you are.", explore: "Explore the cabinet", how: "How we choose", seal: <>Hand-selected<br />with a stone passport</>,
  trust: [["Hand-selected", "Every material is chosen by an experienced hand before it reaches you."], ["A personal passport", "Name, type and care instructions in one quiet document."], ["Nationwide delivery", "Every piece is packed with care and delivered safely across Egypt."]],
  originKicker: "EVERY STONE HAS A ROUTE", originTitle: <>We are not only a stone shop.<br />We preserve <em>its story.</em></>, originBody: "We look for an honest stone, never a repeated look. Then we give it an identity card from its first touch.",
  steps: [["We select", "Natural materials from sources we know and return to."], ["We document", "Every stone receives a record of type and care."], ["We send", "Each piece is wrapped personally and delivered nationwide."]],
  storyKicker: "FROM ONE PERSONAL QUESTION TO ONE PLACE", storyTitle: <>“Where can I find a <em>clean, honest stone</em> with confidence?”</>, storyOne: "The idea began with a love for objects that slow down the day and make room for ourselves. But truly good natural stones were not always close or clearly known, demanding time and knowledge to choose.", storyTwo: "That is why SAKINA exists: we gather these materials in one place, select them honestly, and send the story with every stone so your choice feels meaningful from the first touch to every day after.", asideTop: "FROM HERITAGE MARKETS", asideTitle: <>To every<br />governorate</>, asideBody: "Selected material · calm packaging · passported stone",
  certificateKicker: "NOT AN EXTRA PIECE OF PAPER", certificateTitle: <>This is your stone’s passport.<br /><em>Keep its story.</em></>, certificateBody: "Every selected piece comes with a personal record of its type and care so you always know what you hold in your hands.", certificateLink: "Discover the SAKINA passport", closingKicker: "SAKINA IS WITH YOU, WHEREVER YOU ARE", closing: "Choose quietly. We select honestly. Then we deliver what deserves a place in your daily ritual.", passportName: "STONE IDENTITY CARD", passportType: "TYPE", passportCare: "CARE", passportTypeText: "Selected natural stone", passportCareText: "Personal guidance for each piece",
};

export default function Home() {
  const { language, isArabic } = useLanguage(); const copy = isArabic ? arabicCopy : englishCopy; const Arrow = isArabic ? ArrowLeft : ArrowRight; const trustIcons = [BadgeCheck, ShieldCheck, Truck];
  return <main className={`sakina-home lang-${language}`} dir={isArabic ? "rtl" : "ltr"}>
    <section className="sakina-hero"><div className="hero-grain" /><div className="hero-copy"><div className="route-context route-context--home"><span>{isArabic ? "أنتِ الآن في" : "You are in"}</span><strong>{isArabic ? "الرئيسية" : "Home"}</strong></div><span className="eyebrow eyebrow--light">{copy.heroKicker}</span><h1>{copy.heroTitle}</h1><p>{copy.heroBody}</p><div className="hero-actions"><Link href="/collection" className="sun-button">{copy.explore} <Arrow size={17} /></Link><Link href="/certificate" className="hero-text-link">{copy.how} <ArrowUpLeft size={16} /></Link></div></div><div className="hero-seal"><img src="/assets/sakina-mark_d9d397db.png" alt="" /><span>{copy.seal}</span></div></section>
    <section className="trust-band" aria-label="SAKINA promises">{copy.trust.map(([title, body], index) => { const Icon = trustIcons[index]; return <div key={title}><Icon size={20} /><p><strong>{title}</strong><span>{body}</span></p></div>; })}</section>
    <section className="origin-section" id="origins"><div className="origin-section__heading"><span className="eyebrow">{copy.originKicker}</span><h2>{copy.originTitle}</h2><p>{copy.originBody}</p></div><div className="route-map">{copy.steps.map(([title, body], index) => <div className="route-stop" key={title}><span>0{index + 1}</span><strong>{title}</strong><p>{body}</p></div>)}<div className="route-line" /></div></section>
    <section className="founder-story" id="story"><div className="founder-story__marker"><span>{isArabic ? "سكينة" : "SAKINA"}</span><i /></div><div className="founder-story__copy"><span className="eyebrow">{copy.storyKicker}</span><h2>{copy.storyTitle}</h2><p>{copy.storyOne}</p><p>{copy.storyTwo}</p></div><div className="founder-story__aside"><span>{copy.asideTop}</span><strong>{copy.asideTitle}</strong><p>{copy.asideBody}</p></div></section>
    <section className="certificate-banner"><div className="certificate-banner__copy"><span className="eyebrow">{copy.certificateKicker}</span><h2>{copy.certificateTitle}</h2><p>{copy.certificateBody}</p><Link href="/certificate" className="pine-link">{copy.certificateLink} <Arrow size={16} /></Link></div><div className="passport-card"><div className="passport-card__head"><img src="/assets/sakina-mark_d9d397db.png" alt="" /><span>STONE PASSPORT</span></div><div className="passport-card__title"><small>{copy.passportName}</small><strong>{isArabic ? "شهادة سكينة" : "SAKINA Passport"}</strong></div><dl><div><dt>{copy.passportType}</dt><dd>{copy.passportTypeText}</dd></div><div><dt>{copy.passportCare}</dt><dd>{copy.passportCareText}</dd></div></dl><div className="passport-card__stamp">SAKINA<br />HAND SELECTED</div></div></section>
    <section className="closing-note"><span className="eyebrow">{copy.closingKicker}</span><p>{copy.closing}</p><Link href="/collection" className="collection-home-link">{copy.explore} <Arrow size={15} /></Link></section>
  </main>;
}
